# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLnaTAktBsob5E4lP2Rw5RWKuY0cMpDX
"""

# Step 1: Install required packages
!pip -q install -U langchain-google-genai langchain-core

# Step 2: Enter your Gemini API key safely
import os
import getpass

os.environ["GOOGLE_API_KEY"] = getpass.getpass("Enter your Gemini API Key: ")

# Step 3: Test Gemini with LangChain
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.7,
)

response = llm.invoke([
    HumanMessage(content="Say hello in one sentence")
])

print(response.content)

#step 4 Prompt Template
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful AI tutor."),
    ("human", "Explain {topic} for a beginner in {style} style.")
])

prompt_chain = prompt | llm
response = prompt_chain.invoke({
    "topic": "LangChain prompt templates",
    "style": "simple"
})
print("\nPrompt Template Output:\n", response.content)

#step 5: Simple Chain
simple_chain = prompt | llm
result = simple_chain.invoke({
    "topic": "chains in LangChain",
    "style": "technical but easy"
})
print("\nSimple Chain Output:\n", result.content)

# Reinstall LangChain core packages to ensure all modules are available
!pip install -q -U langchain langchain-community langchain-core

# Step 6: Memory Example (works with current setup)
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage

chat_history = []

memory_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant that remembers the conversation."),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", "{input}")
])

memory_chain = memory_prompt | llm

print("\nMemory Example:")

user_msg_1 = "My name is Manju."
response1 = memory_chain.invoke({
    "chat_history": chat_history,
    "input": user_msg_1
})
print("AI:", response1.content)

chat_history.extend([
    HumanMessage(content=user_msg_1),
    AIMessage(content=response1.content)
])

user_msg_2 = "I am learning LangChain for my internship."
response2 = memory_chain.invoke({
    "chat_history": chat_history,
    "input": user_msg_2
})
print("AI:", response2.content)

chat_history.extend([
    HumanMessage(content=user_msg_2),
    AIMessage(content=response2.content)
])

response3 = memory_chain.invoke({
    "chat_history": chat_history,
    "input": "What is my name and what am I learning?"
})
print("AI:", response3.content)

# 7. Tools + Agent Example
from langchain_core.tools import tool
from langchain.agents import create_agent

@tool
def multiply_numbers(a: int, b: int) -> str:
    """Multiply two integers and return the result."""
    return str(a * b)

@tool
def get_topic_hint(topic: str) -> str:
    """Return a short hint about a technical topic."""
    hints = {
        "langchain": "LangChain connects LLMs with prompts, tools, memory, and data.",
        "vector store": "A vector store enables semantic similarity search.",
    }
    return hints.get(topic.lower(), "No hint available for this topic.")

agent = create_agent(
    model=llm,
    tools=[multiply_numbers, get_topic_hint],
    system_prompt="You are a helpful assistant that uses tools when needed."
)

agent_result = agent.invoke({
    "messages": [
        {"role": "user", "content": "What is 12 multiplied by 9? Also give me a hint about LangChain."}
    ]
})

print("\nAgent Output:\n", agent_result)

# Step 8: Document Loader Example

# Create a sample text file first
with open("sample_notes.txt", "w") as f:
    f.write("""LangChain is a framework for building LLM-powered applications.
It helps developers connect language models with prompts, tools, memory, and external data.
Vector stores are used to retrieve semantically similar documents.
Agents can decide which tool to use based on a user's request.
""")

from langchain_community.document_loaders import TextLoader

loader = TextLoader("sample_notes.txt")
documents = loader.load()

print("Loaded document content:\n")
print(documents[0].page_content)

# Step 9: Simple vector-like retrieval demo without OpenAI API

texts = [doc.page_content for doc in documents]

query = "What helps retrieve similar documents?"

results = []
for text in texts:
    score = 0
    for word in query.lower().split():
        if word in text.lower():
            score += 1
    results.append((score, text))

results = sorted(results, reverse=True)

print("\nRetrieval Results:")
for i, (score, text) in enumerate(results[:2], 1):
    print(f"\nResult {i} (score={score}):")
    print(text)

"""## Conclusion

In this assignment, I implemented and tested multiple LangChain components end‑to‑end in a Colab notebook.  
From the first cell to the last, I moved from a simple LLM call to a small but complete GenAI pipeline.

**Key takeaways:**
- Chat models like `ChatOpenAI` / Gemini can be called through a clean LangChain interface.
- `PromptTemplate` and `ChatPromptTemplate` replace hard‑coded strings and make prompts reusable and dynamic.
- Chaining prompts with the LLM lets me build modular pipelines instead of one‑off calls.
- Maintaining a conversation history acts as memory so the model can answer context‑aware questions.
- Tools and agents show how LLMs can call Python functions to perform real work beyond text generation.
- Document loaders and retrieval logic demonstrate how to bring external knowledge into the LLM workflow.

This task helped me connect the **theory of LangChain architecture** with working Python code.  
I now understand how real‑world GenAI applications are built by composing LLMs with prompts, tools, memory, and data sources in a structured way.
"""

