# -*- coding: utf-8 -*-
"""NLP_Token_Classification_POS_Tagging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8Ytt2xRW9BWLhFEbOESOIbB8_N9J0xA
"""

!pip install transformers datasets seqeval -q
print("Done")

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
    pipeline
)
from seqeval.metrics import (
    classification_report,
    f1_score,
    precision_score,
    recall_score
)

print("All imports done")
print("GPU:", torch.cuda.is_available())

dataset = load_dataset("wikiann", "en")
print(dataset)
print("\nSample:")
print(dataset["train"][0])

label_list = dataset["train"]\
    .features["ner_tags"].feature.names

id2label = {
    i: label
    for i, label in enumerate(label_list)
}
label2id = {
    label: i
    for i, label in enumerate(label_list)
}

print("Labels:", label_list)
print("Total:", len(label_list))

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased"
)
print("Tokenizer loaded")

# Already done in Cell 4
print("Label mapping ready")
print("id2label:", id2label)

def tokenize_and_align_labels(examples):
    tokenized_inputs = tokenizer(
        examples["tokens"],
        truncation=True,
        is_split_into_words=True,
        padding="max_length",
        max_length=128
    )
    all_labels = []
    for i, labels in enumerate(
            examples["ner_tags"]):
        word_ids = tokenized_inputs\
            .word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []
        for word_idx in word_ids:
            if word_idx is None:
                label_ids.append(-100)
            elif word_idx != previous_word_idx:
                label_ids.append(
                    labels[word_idx])
            else:
                label_ids.append(-100)
            previous_word_idx = word_idx
        all_labels.append(label_ids)
    tokenized_inputs["labels"] = all_labels
    return tokenized_inputs

print("Alignment function defined")

tokenized_dataset = dataset.map(
    tokenize_and_align_labels,
    batched=True
)
print("Tokenization done")

model = AutoModelForTokenClassification\
    .from_pretrained(
        "distilbert-base-uncased",
        num_labels=len(label_list),
        id2label=id2label,
        label2id=label2id
    )
print("Model loaded")
print("Num labels:", len(label_list))

data_collator = DataCollatorForTokenClassification(
    tokenizer=tokenizer
)
print("Data collator ready")

def compute_metrics(pred):
    predictions, labels = pred
    predictions = np.argmax(
        predictions, axis=2)
    true_predictions = [
        [label_list[p]
         for p, l in zip(prediction, label)
         if l != -100]
        for prediction, label
        in zip(predictions, labels)
    ]
    true_labels = [
        [label_list[l]
         for p, l in zip(prediction, label)
         if l != -100]
        for prediction, label
        in zip(predictions, labels)
    ]
    return {
        "precision": precision_score(
            true_labels, true_predictions),
        "recall": recall_score(
            true_labels, true_predictions),
        "f1": f1_score(
            true_labels, true_predictions)
    }

print("compute_metrics defined")

training_args = TrainingArguments(
    output_dir="./pos_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    fp16=True,
    logging_steps=100,
    load_best_model_at_end=True,
    report_to="none"
)
print("Training args defined")

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)
print("Trainer ready")

print("Training started...")
trainer.train()

results = trainer.evaluate(
    tokenized_dataset["test"])

print("\n===== RESULTS =====")
for key, val in results.items():
    print(f"{key}: {round(val, 4)}")

predictions, labels, _ = trainer.predict(
    tokenized_dataset["test"])
predictions = np.argmax(predictions, axis=2)

true_predictions = [
    [label_list[p]
     for p, l in zip(prediction, label)
     if l != -100]
    for prediction, label
    in zip(predictions, labels)
]
true_labels = [
    [label_list[l]
     for p, l in zip(prediction, label)
     if l != -100]
    for prediction, label
    in zip(predictions, labels)
]

print("Classification Report:")
print(classification_report(
    true_labels, true_predictions))

nlp_pipeline = pipeline(
    "token-classification",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple"
)

sentences = [
    "John works at Google in California",
    "Apple is buying a startup in London",
    "Barack Obama was born in Hawaii"
]

for sentence in sentences:
    print(f"\nInput: {sentence}")
    result = nlp_pipeline(sentence)
    print("Tags:")
    for r in result:
        print(f"  {r['word']:15} → "
              f"{r['entity_group']}")

print("""
========================================
ASSIGNMENT 5 - TOKEN CLASSIFICATION
========================================
Model   : distilbert-base-uncased
Dataset : WikiANN English
Task    : NER / POS Tagging
Epochs  : 3
LR      : 2e-5

Labels:
- O     : Outside
- B-PER : Person begin
- I-PER : Person inside
- B-ORG : Organization begin
- I-ORG : Organization inside
- B-LOC : Location begin
- I-LOC : Location inside

Key Learning:
Token classification assigns a label
to each individual token in a sentence
rather than the whole sentence.
========================================
""")

